### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by davidhadas** [eventEmitter/leaky-bucket#4]
On a mac.

bash-3.2$ node -v
v8.9.4
bash-3.2$ npm -v
5.6.0
bash-3.2$ npm install leaky-bucket
npm WARN docker_web_app@1.0.0 No repository field.
npm WARN docker_web_app@1.0.0 No license field.

+ leaky-bucket@2.1.1
added 71 packages in 3.584s
bash-3.2$ node 
> var LeakyBucket = require('leaky-bucket');
TypeError: path must be a string or Buffer
    at Object.fs.statSync (fs.js:948:11)
    at classConstructor.init (/Users/davidh/WebstormProjects/webClientSimulator/node_modules/ee-log/lib/Logger.js:59:15)
    at new classConstructor (/Users/davidh/WebstormProjects/webClientSimulator/node_modules/ee-class/src/class.js:162:47)
    at /Users/davidh/WebstormProjects/webClientSimulator/node_modules/ee-log/lib/Logger.js:52:12

**Comment by linaGirl** [comment]
i just released a fix, hope it works for you. https://www.npmjs.com/package/leaky-bucket
